language: node_js
node_js:
- node
cache: yarn
script:
- "./bin/run --version"
- "./bin/run --help"
- yarn run test
notifications:
  slack:
    secure: qATgBf6C1zdQ+/X8+VROSLtrOYhVV45fKkUACRkmOOX/TME/mF/yYA2Ay2itnngPxmFkIKXZ9q33ko+ld+WA8CgD6u+Rcllr+rsnxEbE83ts+01cM879BPX4T9ykO8/Jzftup5xH4nIJVvwUyPC6H0C/NBzCsAYqjXACdc4FAy8qghKw5fvxsB+GVW79UwsTn+L6ELJ1WifvNg2+Iw6AOKzTscdn0jFsm7qxiaDNvhmKnJAP7pwQvsghGz7XefhfXyDTfejQR5w6siq/0BWANgOVMy95GauUm9bIN0gaIKPyqgPfwT74eXoMvg02k+l8Gx+UDS3LptmFte0Pl63Ipp+GUWAImfvBFlmj8yB4TyEXtLW3kxrfQsHO2cocUFjlvlEX7VTgBKVmznYFRnyNP7szg2BAidEbd0yURyKZgnEXamlLjL3U1cBbGxEyETrDBbULZxi/Zs1c5CJoIUr7yyjbbHmMyPheWCP35eoUZkQiKaXndfZdQrEfr0s21zTJoK2PNkhtcaezY7bpw+SStZDO8z6USWc48a13rR7Sc6vHLZ5YHdLHobwR2zHZTIMY5+m1ncjxDEQCMFJdinbEk2dLMG3FT234xznPfOkmC9FhvOFRSsz5+HTCNsT24yPdib5MkrmvKsBN6ETuOJOlv8O4xwdUlzwM6GSFtHlw+pw=
